Repository junpotatoes/cash-view, pull requests merged in 2023-02, with the labels that each got.

#4 로그인 컴포넌트 구현
  src/components/LoginForm.tsx
  src/pages/login&signup/index.tsx
  src/styles/login.ts
Labels: Feat, Design

#5 회원가입 컴포넌트 구현
  src/components/SignUpForm.tsx
  src/pages/login&signup/index.tsx
  src/styles/signup.ts
Labels: Feat, Design

#7 로그인 페이지 폴더 구조변경
  src/components/sign/LoginForm.tsx
  src/components/sign/SignUpForm.tsx
  src/pages/sign/index.tsx
  src/styles/sign/login.ts
  src/styles/sign/signup.ts
Labels: Docs, Rename

#8 GNB 컴포넌트 구현
  custom.d.ts
  package-lock.json
  package.json
  src/App.tsx
  src/assets/Icon/menuIcon.svg
  src/components/Layout/Header.tsx
  src/styles/Layout/Header.style.ts
  tsconfig.json
  webpack.config.js
Labels: Feat, Design

#13 회원가입 컴포넌트 기능구현
  db.json
  src/components/sign/SignUpForm.tsx
Labels: Feat

#14 로그인 컴포넌트 기능 구현
  src/components/sign/LoginForm.tsx
  src/components/sign/SignUpForm.tsx
Labels: Feat

#16 login 페이지 스타일 구조 변경
  src/components/sign/LoginForm.tsx
  src/components/sign/SignUpForm.tsx
  src/pages/sign/index.tsx
  src/styles/sign/login.style.ts
  src/styles/sign/signup.style.ts
Labels: Style

#18 AddHistory 컴포넌트 구현
  db.json
  package-lock.json
  package.json
  src/components/Calendar/addhistory/AddHistory.tsx
  src/components/Calendar/addhistory/AddHistoryForm.tsx
  src/components/Calendar/addhistory/ExpensesCategory.tsx
  src/components/Calendar/addhistory/IncomeCategory.tsx
  src/components/Calendar/addhistory/SelectClass.tsx
  src/components/Datepicker.tsx
  src/styles/historymodal/history.style.ts
Labels: Feat, Design

#27 AddHistory 컴포넌트 redux-toolkit 적용
  db.json
  package-lock.json
  package.json
  src/components/Calendar/addhistory/AddHistoryForm.tsx
  src/components/Chart/BarChart.tsx
  src/components/Chart/ExpensesPieChart.tsx
  src/components/Chart/IncomePieChart.tsx
  src/components/Datepicker.tsx
  src/components/Layout/Route.tsx
  src/pages/Chart.tsx
  src/store/calendarSlice.ts
  src/store/historySlice.ts
Labels: Feat

#34 AddHistoryForm userId POST
  db.json
  src/components/Calendar/addhistory/AddHistoryForm.tsx
  src/components/Calendar/addhistory/EditHistory.tsx
Labels: Feat

#39 컴포넌트 연결
  src/assets/Icon/deleteIcon.svg
  src/assets/Icon/updateIcon.svg
  src/components/Calendar/History/CalendarHistory.tsx
  src/components/Calendar/History/HistoryDetail.tsx
  src/components/Calendar/History/Modal/AddHistory.tsx
  src/components/Calendar/History/Modal/AddHistoryForm.tsx
  src/components/Calendar/History/Modal/EditHistory.tsx
  src/components/Calendar/History/Modal/EditHistoryForm.tsx
  src/components/Calendar/History/Modal/ExpensesCategory.tsx
  src/components/Calendar/History/Modal/IncomeCategory.tsx
  src/components/Calendar/History/Modal/SelectClass.tsx
  src/components/Calendar/Modal/Datepicker.tsx
  src/components/Calendar/addhistory/AddHistory.tsx
  src/components/Calendar/addhistory/SelectClass.tsx
  src/components/Layout/Header.tsx
  src/components/Layout/Route.tsx
  src/pages/Calendar.tsx
  src/styles/calendar/Addhistory/AddHistory.style.ts
  src/styles/calendar/History/HistoryDetail.style.ts
Labels: Feat, Design

#40 Feature/#38
  src/components/Chart/BarChart.tsx
  src/components/Chart/ExpensesPieChart.tsx
  src/components/Chart/IncomePieChart.tsx
  src/pages/Chart.tsx
Labels: Feat

#44 지난달 지출 비교 로직 수정
  src/components/Calendar/History/HistoryComparison.tsx
  src/styles/calendar/Main/CalendarDate.style.ts
Labels: Feat, Design

#46 다음달 날짜 지출/수입 표시
  src/components/Calendar/Main/CalendarDate.tsx
Labels: Feat

#48 선택한 날짜 유지 로직 구현
  src/Index.tsx
  src/components/sign/LoginForm.tsx
  src/store/calendarSlice.ts
Labels: Feat
