Repository junpotatoes/cash-view, pull requests merged in 2023-03, with the labels that each got.

#50 컴포넌트 분리
  src/components/Calendar/Header/HistoryHeader.tsx
  src/components/Calendar/History/Comparison/ComparisonPrevMonth.tsx
  src/components/Calendar/History/Comparison/ComparisonToday.tsx
  src/components/Calendar/History/HistoryComparison.tsx
  src/components/Calendar/History/HistoryDetail.tsx
  src/components/Calendar/Main/CalendarDate.tsx
  src/components/Calendar/Main/Date/CurrentMonthDate.tsx
  src/components/Calendar/Main/Date/MobileMonthDate.tsx
  src/components/Calendar/Main/Date/NextMonthDate.tsx
  src/components/Calendar/Main/Date/PrevMonthDate.tsx
  src/components/Calendar/Main/HistoryMain.tsx
Labels: Refactor

#53 SignUpForm 컴포넌트 기본이미지 post 구현
  src/components/sign/SignUpForm.tsx
Labels: Feat

#54 GNB 사용자정보 수정
  src/components/Layout/Header.tsx
  src/styles/Layout/Header.style.ts
Labels: Feat, Design

#57 axios API 모듈화
  src/api/customAxios.ts
  src/components/Calendar/History/Modal/AddHistoryForm.tsx
  src/components/Calendar/History/Modal/EditHistory.tsx
  src/components/Calendar/History/Modal/EditHistoryForm.tsx
  src/components/Calendar/Main/HistoryMain.tsx
  src/components/Chart/BarChart.tsx
  src/components/Chart/ExpensesPieChart.tsx
  src/components/Chart/IncomePieChart.tsx
  src/components/Layout/Header.tsx
  src/components/sign/LoginForm.tsx
  src/components/sign/SignUpForm.tsx
  src/pages/Calendar.tsx
  src/pages/Chart.tsx
  src/pages/Setting.tsx
Labels: Refactor

#58 Setting 페이지 css 구조 변경
  src/pages/Setting.tsx
  src/styles/Setting/Setting.style.ts
Labels: Style

#59 Chart 페이지 수정
  src/components/Chart/ExpensesPieChart.tsx
  src/components/Chart/IncomePieChart.tsx
  src/pages/Chart.tsx
  src/styles/Chart/Chart.style.ts
Labels: Feat, Style

#60 웹팩 절대경로 적용
  src/App.tsx
  src/Index.tsx
  src/components/Calendar/Header/CalendarHeader.tsx
  src/components/Calendar/Header/HistoryHeader.tsx
  src/components/Calendar/History/CalendarHistory.tsx
  src/components/Calendar/History/Comparison/ComparisonPrevMonth.tsx
  src/components/Calendar/History/Comparison/ComparisonToday.tsx
  src/components/Calendar/History/HistoryComparison.tsx
  src/components/Calendar/History/HistoryDate.tsx
  src/components/Calendar/History/HistoryDetail.tsx
  src/components/Calendar/History/Modal/AddHistory.tsx
  src/components/Calendar/History/Modal/AddHistoryForm.tsx
  src/components/Calendar/History/Modal/EditHistory.tsx
  src/components/Calendar/History/Modal/EditHistoryForm.tsx
  src/components/Calendar/History/Modal/ExpensesCategory.tsx
  src/components/Calendar/History/Modal/IncomeCategory.tsx
  src/components/Calendar/History/Modal/SelectClass.tsx
  src/components/Calendar/Main/CalendarDate.tsx
  src/components/Calendar/Main/CalendarDay.tsx
  src/components/Calendar/Main/CalendarMain.tsx
  src/components/Calendar/Main/Date/CurrentMonthDate.tsx
  src/components/Calendar/Main/Date/MobileMonthDate.tsx
  src/components/Calendar/Main/Date/NextMonthDate.tsx
  src/components/Calendar/Main/Date/PrevMonthDate.tsx
  src/components/Calendar/Main/HistoryMain.tsx
  src/components/Calendar/Modal/DateModal.tsx
  src/components/Calendar/Modal/ModalButton.tsx
  src/components/Calendar/Modal/MonthModal.tsx
  src/components/Calendar/Modal/MonthModalHeader.tsx
  src/components/Calendar/Modal/MonthModalMain.tsx
  src/components/Chart/BarChart.tsx
  src/components/Chart/ExpensesPieChart.tsx
  src/components/Chart/IncomePieChart.tsx
  src/components/Layout/Header.tsx
  src/components/Layout/Main.tsx
  src/components/Layout/Route.tsx
  src/components/sign/LoginForm.tsx
  src/components/sign/SignUpForm.tsx
  src/hooks/store.ts
  src/pages/Calendar.tsx
  src/pages/Chart.tsx
  src/pages/Setting.tsx
  src/pages/Sign.tsx
  src/store/index.ts
  tsconfig.json
  webpack.config.js
Labels: Refactor

#65 캘린더 컴포넌트 수정
  src/components/Calendar/History/Comparison/ComparisonToday.tsx
  src/components/Calendar/History/HistoryComparison.tsx
  src/components/Calendar/Main/Date/CurrentMonthDate.tsx
  src/components/Calendar/Main/Date/MobileMonthDate.tsx
  src/components/Calendar/Main/Date/NextMonthDate.tsx
  src/components/Calendar/Main/Date/PrevMonthDate.tsx
  src/components/Calendar/Main/HistoryMain.tsx
  src/components/Calendar/Modal/MonthModalHeader.tsx
  src/store/calendarSlice.ts
  src/styles/Calendar/History/CalendarHistory.style.ts
  src/styles/Calendar/History/HistoryComparison.style.ts
  src/styles/Calendar/History/HistoryDetail.style.ts
  src/styles/Calendar/Main/CalendarDate.style.ts
Labels: Feat, Design

#69 오늘 날짜 디자인 수정
  src/components/Calendar/Main/Date/CurrentMonthDate.tsx
  src/components/Calendar/Main/Date/NextMonthDate.tsx
  src/components/Calendar/Main/Date/PrevMonthDate.tsx
  src/styles/Calendar/Main/CalendarDate.style.ts
Labels: Design

#72 월 이동시 날짜 수정
  src/store/calendarSlice.ts
Labels: Feat

#73 로그인 페이지 CSS 수정
  src/styles/Sign/Login.style.ts
  src/styles/Sign/Signup.style.ts
Labels: Design

#76 내역 추가/수정 비동기 처리
  src/components/Calendar/History/Modal/AddHistoryForm.tsx
  src/components/Calendar/History/Modal/EditHistoryForm.tsx
Labels: Feat

#77 Feature/#74
  src/components/Chart/BarChart.tsx
  src/components/Chart/ExpensesPieChart.tsx
  src/components/Chart/IncomePieChart.tsx
  src/pages/Chart.tsx
  src/styles/Chart/Chart.style.ts
Labels: Feat, Design

#79 설정 페이지 css 수정
  src/styles/Setting/Setting.style.ts
Labels: Design

#81 모달 백아웃 수정
  src/App.tsx
  src/components/Calendar/Header/CalendarHeader.tsx
  src/components/Calendar/History/Modal/AddHistory.tsx
  src/components/Calendar/History/Modal/EditHistory.tsx
  src/components/Calendar/Main/CalendarDate.tsx
  src/components/Calendar/Main/Date/CurrentMonthDate.tsx
  src/styles/Calendar/Addhistory/AddHistory.style.ts
  src/styles/Calendar/Main/CalendarDate.style.ts
  src/styles/Global/global.style.ts
  src/styles/Global/modal.style.ts
  src/styles/Global/theme.style.ts
  src/styles/Layout/Header.style.ts
Labels: Feat, Design

#82 총 지출/수입 구현
  src/components/Calendar/Amount/ Expenditure.tsx
  src/components/Calendar/Amount/Income.tsx
  src/components/Calendar/History/Comparison/ComparisonPrevMonth.tsx
  src/components/Calendar/History/Comparison/ComparisonToday.tsx
  src/pages/Calendar.tsx
  src/styles/Calendar/Calendar.style.ts
Labels: Feat, Design

#84 모달 백아웃 GNB 적용
  src/styles/Calendar/Main/CalendarDate.style.ts
  src/styles/Layout/Header.style.ts
Labels: Design

#85 알림창 구현
  src/components/Alert/Alert.tsx
  src/components/Calendar/History/Modal/AddHistoryForm.tsx
  src/components/Calendar/History/Modal/EditHistoryForm.tsx
  src/components/Calendar/History/Modal/ExpensesCategory.tsx
  src/components/Calendar/History/Modal/IncomeCategory.tsx
  src/components/Calendar/History/Modal/SelectClass.tsx
  src/components/Calendar/Main/HistoryMain.tsx
  src/components/Sign/LoginForm.tsx
  src/components/Sign/SignUpForm.tsx
  src/pages/Calendar.tsx
  src/pages/Setting.tsx
  src/pages/Sign.tsx
  src/store/calendarSlice.ts
  src/store/historySlice.ts
  src/store/index.ts
  src/styles/Alert/Alert.style.ts
  src/styles/Sign/Login.style.ts
  src/styles/Sign/Signup.style.ts
Labels: Feat, Design

#87 캘린더 수입/지출 수정
  src/components/Calendar/Amount/Expenditure.tsx
  src/components/Calendar/Main/Date/CurrentMonthDate.tsx
  src/pages/Calendar.tsx
Labels: Design

#90 알림창 수정
  src/App.tsx
  src/components/Alert/Alert.tsx
  src/components/Calendar/Amount/Expenditure.tsx
  src/components/Calendar/Amount/Income.tsx
  src/components/Calendar/Header/HistoryHeader.tsx
  src/components/Calendar/History/CalendarHistory.tsx
  src/components/Calendar/History/Comparison/ComparisonPrevMonth.tsx
  src/components/Calendar/History/Comparison/ComparisonToday.tsx
  src/components/Calendar/History/HistoryComparison.tsx
  src/components/Calendar/History/HistoryDetail.tsx
  src/components/Calendar/History/Modal/AddHistory.tsx
  src/components/Calendar/History/Modal/AddHistoryForm.tsx
  src/components/Calendar/History/Modal/EditHistory.tsx
  src/components/Calendar/History/Modal/EditHistoryForm.tsx
  src/components/Calendar/Main/CalendarDate.tsx
  src/components/Calendar/Main/CalendarMain.tsx
  src/components/Calendar/Main/HistoryMain.tsx
  src/components/Chart/BarChart.tsx
  src/components/Chart/ExpensesPieChart.tsx
  src/components/Chart/IncomePieChart.tsx
  src/components/Layout/Route.tsx
  src/components/Sign/LoginForm.tsx
  src/components/Sign/SignUpForm.tsx
  src/pages/Calendar.tsx
  src/pages/Chart.tsx
  src/styles/Sign/Login.style.ts
  src/styles/Sign/Signup.style.ts
Labels: Feat, Design

#92 설정 페이지 css 수정
  src/styles/Setting/Setting.style.ts
Labels: Design

#93 chart 페이지 label 합계 에러 및 css 수정
  src/components/Chart/ExpensesPieChart.tsx
  src/components/Chart/IncomePieChart.tsx
  src/styles/Chart/Chart.style.ts
Labels: Design, Fix

#97 지출/수입 합계 구현
  src/components/Calendar/Amount/Expenditure.tsx
  src/components/Calendar/Amount/Income.tsx
  src/components/Calendar/Amount/Total.tsx
  src/pages/Calendar.tsx
  src/styles/Calendar/Calendar.style.ts
Labels: Feat, Design

#99 로그인 시 내역 데이터 불러오기
  src/components/Layout/Route.tsx
  src/components/Sign/LoginForm.tsx
Labels: Fix

#107 #106 - design: BarChartBox 모바일 환경 width 수정
  src/styles/Chart/Chart.style.ts
Labels: Design

#109 내역 추가/수정 form 수정
  src/components/Calendar/History/HistoryDetail.tsx
  src/components/Calendar/History/HistoryHeader.tsx
  src/components/Calendar/History/HistoryItem.tsx
  src/components/Calendar/History/HistoryMain.tsx
  src/components/Calendar/History/Modal/AddHistoryForm.tsx
  src/components/Calendar/History/Modal/EditHistoryForm.tsx
  src/components/Calendar/Main/HistoryMain.tsx
Labels: Fix

#111 로그인/회원가입 페이지 수정
  src/components/Sign/LoginForm.tsx
  src/styles/Sign/Signup.style.ts
Labels: Feat, Design
